---
  parserOptions:
    ecmaVersion: 6
    ecmaFeatures:
      jsx: true
  plugins:
    - "react"
  extends:
    - "eslint:recommended"
    - "plugin:react/recommended"
  globals:
    require: false
    module: false
    fetch: false
    console: false
    document: false
    Map: false
